version: "3.9"

services:

  ##############################
  # Document Service - Upload & Parsing
  ##############################
  document-service:
    build: ./document-service
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - indexing-service
    networks:
      - hubnet

  ##############################
  # Weaviate
  ##############################
  vector-db:
    image: semitechnologies/weaviate:latest
    ports:
      - "8083:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - hubnet

  ##############################
  # Indexing Service - Embeddings
  ##############################
  indexing-service:
    build: ./indexing-service
    ports:
      - "8084:8080"
    depends_on:
      - vector-db
      - kafka
    environment:
      - VECTOR_DB_URL=http://vector-db:8080
    networks:
      - hubnet

  ##############################
  # Query Service - Q&A + Doc Gen
  ##############################
  query-service:
    build: ./query-service
    ports:
      - "8085:8080"
    depends_on:
      - ollama
      - vector-db
      - indexing-service
    environment:
      - OLLAMA_URL=http://ollama:11434
      - VECTOR_DB_URL=http://vector-db:8080
    networks:
      - hubnet

  ##############################
  # Kafka
  ##############################
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_KRAFT_CLUSTER_ID: my-cluster-id
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - hubnet

  ##############################
  # Kafka UI
  ##############################
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_CONSUMER_PROPERTIES_GROUP_ID=kafka-ui-group
    depends_on:
      - kafka
    networks:
      - hubnet

  ##############################
  # Ollama LLM - model installed llama3, nomic-embed-text, mxbai-embed-large
  ##############################
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - hubnet

networks:
  hubnet:
    driver: bridge

volumes:
  weaviate_data:
  ollama_models:
  kafka-data: